name: flutter_anime_manga_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  salomon_bottom_bar: ^3.3.2
  oktoast: ^3.4.0
  carousel_slider: ^4.2.1
  numberpicker: ^2.1.2
  rive: ^0.12.3

  # Navigation
  go_router: ^12.1.1

  # State Management
  flutter_bloc: ^8.1.3

  # Http
  dio: ^5.3.4

  # Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2

  # Utility
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  shimmer: ^3.0.0
  intl: ^0.18.1
  search_choices: ^2.2.7
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  youtube_player_flutter: ^8.1.2
  animations: ^2.0.8
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  webview_flutter: ^4.4.2
  lottie: ^3.0.0-alpha.2
  shared_preferences: ^2.2.2


  # Splash Screen
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  color: '#4F3FEC'
  color_dark: '#4F3FEC'
  image: assets/images/wallpaper.png
  image_dark: assets/images/wallpaper.png

  android_12:
    color: '#4F3FEC'
    color_dark: '#4F3FEC'
    image: assets/images/wallpaper.png
    image_dark: assets/images/wallpaper.png


  web: false





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/images/wallpaper.png
    - assets/rive/
    - assets/lottie/


