name: flutter_anime_manga_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  salomon_bottom_bar: ^3.3.2
  flutter_native_splash: ^2.3.5
  oktoast: ^3.3.2+1
  carousel_slider: ^4.2.1

  # Navigation
  go_router: ^12.1.1

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Http
  dio: ^5.3.3

  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0

  # Utility
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  shimmer: ^3.0.0
  intl: ^0.18.1
  search_choices: ^2.2.7
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  youtube_player_flutter: ^8.1.2
  animations: ^2.0.8
  share_plus: ^7.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/


